"""BUS SERVO CONTROLLER PRESETS"""

FRAME_HEADER = 0x55
CMD_SERVO_MOVE = 0x03
CMD_ACTION_GROUP_RUN = 0x06
CMD_ACTION_GROUP_STOP = 0x07
ACTION_GROUP_COMPLETE = 0x08
CMD_ACTION_GROUP_SPEED = 0x0B
CMD_GET_POSITIONS = 0x15
CMD_GET_BATTERY_VOLTAGE = 0x0F
CMD_MULT_SERVO_UNLOAD = 0x14

N_SERVOS = 23  # 18 for legs, 5 for arm
SERVO_TYPE = "lx-224 HV"  # "HTD-45H" has the same usage, but higher current draw